typography_spectrum: 0.9918110480066389
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4576603714376688
  lightness: 0.8260627177078277
  saturation: 0.8038909973111004
  rhythmicContrast: 0.1617348762229085
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7085947922896594
analytics:
  google: null
  facebook: null
  twitter: null
name: anechoic
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Anechoic
description: I don't know how I got here
purpose: []
